### ISSUE TITLE
Handle `Iterable[str]` as input in reader

### ISSUE THREAD

**Issue by jonathan-s** [medialab/casanova#152] opened 2024-06-18 09:46 UTC
At the time of writing it's currently only handling `Iterable[list[str]]`, It would be quite handy if it handled `Iterable[str]`, where str is the format of a single csv line.

**Comment by Yomguithereal** [comment] 2024-07-05 09:50
This would be nice indeed. But I don't think this polymorphism can work without an addition kwarg on the reader however. I will close this issue though because it is a duplicate of #47

**Closed by Yomguithereal** 2024-07-05 09:50 UTC
Labels: duplicate
